/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.
===============================================================================
*/

--Magnitude Analysis
-- measures by dimensions

--total customers by countries 
SELECT [country], 
COUNT(DISTINCT([customer_key])) AS total_customers
FROM [gold].[dim_customers]
GROUP BY [country]
order by total_customers desc

--total customers by gender
SELECT [gender], 
COUNT(DISTINCT([customer_key])) AS total_customers
FROM [gold].[dim_customers]
GROUP BY [gender]
order by total_customers desc

--total products  by category
SELECT [category], 
COUNT(DISTINCT([product_key])) AS total_products
FROM [gold].[dim_products]
GROUP BY [category]
order by total_products desc

--avg cost in each category
SELECT [category], 
AVG([cost]) AS average_cost
FROM [gold].[dim_products]
GROUP BY [category]
order by average_cost desc

--total revenue generated by each category

SELECT p.[category], 
SUM(s.[sales_amount]) as total_revenue
FROM [gold].[fact_sales] s
LEFT JOIN [gold].[dim_products] p
ON s.[product_key] = p.[product_key]
GROUP BY p.[category]
order by total_revenue desc

--total revenue generated by each customer
SELECT c.[customer_key],
c.[first_name],
c.[last_name],
SUM(s.[sales_amount]) as total_revenue
FROM [gold].[fact_sales] s
LEFT JOIN [gold].[dim_customers] c
ON s.[customer_key] = c.[customer_key]
GROUP BY c.[customer_key],c.[first_name],c.[last_name]
order by total_revenue desc

--Sold items across countries
SELECT c.[country],
SUM(s.[quantity]) as total_sold_items
FROM [gold].[fact_sales] s
LEFT JOIN [gold].[dim_customers] c
ON s.[customer_key] = c.[customer_key]
GROUP BY c.[country]
order by total_sold_items desc

